###

POST http://127.0.0.1:3001/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzMzc4YmE2YmQwNWZlNjhkNzQ2Nzc2ZjZlZDhmMTEyM2U4MWI2YTUifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2dnME16TTBOVGs1T0JJR1oybDBhSFZpIiwiYXVkIjoid2VidGVjaC1mcm9udGVuZCIsImV4cCI6MTYwODMwNzI4NSwiaWF0IjoxNjA4MjIwODg1LCJhdF9oYXNoIjoiM3VFRUlDLTdsZnBNVEw0MGI0RnhpUSIsImVtYWlsIjoibWRlY2FtcG91QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.q6qZtncJ-Xzmwg_nVCgLNchFGoEsw7Hi8-l7hyIZlw9D2ngQlu1KcLQUi4U8KPC1G1xLloARYcURt7P89ThXPKq8FOJsBuE29PtPdIBX3fGTlqzkjCemGbLIfrVdMSul7HX-fiA35EkThNFabmZ0-uZWI9YIORHakw1nID4nTeTfNf36aJ3zJ3vqBgqOEA3-J0TXclCpa2YGQYR3HLBbUgXMHMGfUkNzFe-6jbeHbyPg1zSbVbM0OaH1Tl5gqFvvIXWbzbEP1IXdZeiojzKawGeSnDzqsBxravxWmPnLdSSWTLukxqcS6k9D9NiplFFJs0yybRD0TqB_219rstHsuw

{
  "name": "Mathieu"
}

###

POST http://127.0.0.1:3001/channels HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzMzc4YmE2YmQwNWZlNjhkNzQ2Nzc2ZjZlZDhmMTEyM2U4MWI2YTUifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2dnME16TTBOVGs1T0JJR1oybDBhSFZpIiwiYXVkIjoid2VidGVjaC1mcm9udGVuZCIsImV4cCI6MTYwODMwNzI4NSwiaWF0IjoxNjA4MjIwODg1LCJhdF9oYXNoIjoiM3VFRUlDLTdsZnBNVEw0MGI0RnhpUSIsImVtYWlsIjoibWRlY2FtcG91QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.q6qZtncJ-Xzmwg_nVCgLNchFGoEsw7Hi8-l7hyIZlw9D2ngQlu1KcLQUi4U8KPC1G1xLloARYcURt7P89ThXPKq8FOJsBuE29PtPdIBX3fGTlqzkjCemGbLIfrVdMSul7HX-fiA35EkThNFabmZ0-uZWI9YIORHakw1nID4nTeTfNf36aJ3zJ3vqBgqOEA3-J0TXclCpa2YGQYR3HLBbUgXMHMGfUkNzFe-6jbeHbyPg1zSbVbM0OaH1Tl5gqFvvIXWbzbEP1IXdZeiojzKawGeSnDzqsBxravxWmPnLdSSWTLukxqcS6k9D9NiplFFJs0yybRD0TqB_219rstHsuw

{
  "name": "Non"
}

###

GET http://127.0.0.1:3001/users/bWRlY2FtcG91QGdtYWlsLmNvbQ==/channels HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzMzc4YmE2YmQwNWZlNjhkNzQ2Nzc2ZjZlZDhmMTEyM2U4MWI2YTUifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2dnME16TTBOVGs1T0JJR1oybDBhSFZpIiwiYXVkIjoid2VidGVjaC1mcm9udGVuZCIsImV4cCI6MTYwODMwNzI4NSwiaWF0IjoxNjA4MjIwODg1LCJhdF9oYXNoIjoiM3VFRUlDLTdsZnBNVEw0MGI0RnhpUSIsImVtYWlsIjoibWRlY2FtcG91QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.q6qZtncJ-Xzmwg_nVCgLNchFGoEsw7Hi8-l7hyIZlw9D2ngQlu1KcLQUi4U8KPC1G1xLloARYcURt7P89ThXPKq8FOJsBuE29PtPdIBX3fGTlqzkjCemGbLIfrVdMSul7HX-fiA35EkThNFabmZ0-uZWI9YIORHakw1nID4nTeTfNf36aJ3zJ3vqBgqOEA3-J0TXclCpa2YGQYR3HLBbUgXMHMGfUkNzFe-6jbeHbyPg1zSbVbM0OaH1Tl5gqFvvIXWbzbEP1IXdZeiojzKawGeSnDzqsBxravxWmPnLdSSWTLukxqcS6k9D9NiplFFJs0yybRD0TqB_219rstHsuw

###

GET http://127.0.0.1:3001/users/bWRlY2FtcG91QGdtYWlsLmNvbQ== HTTP/1.1
Content-Type: application/json

###

GET http://127.0.0.1:3001/users/byname/Mathieu HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUzMzc4YmE2YmQwNWZlNjhkNzQ2Nzc2ZjZlZDhmMTEyM2U4MWI2YTUifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2dnME16TTBOVGs1T0JJR1oybDBhSFZpIiwiYXVkIjoid2VidGVjaC1mcm9udGVuZCIsImV4cCI6MTYwODMwNzI4NSwiaWF0IjoxNjA4MjIwODg1LCJhdF9oYXNoIjoiM3VFRUlDLTdsZnBNVEw0MGI0RnhpUSIsImVtYWlsIjoibWRlY2FtcG91QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.q6qZtncJ-Xzmwg_nVCgLNchFGoEsw7Hi8-l7hyIZlw9D2ngQlu1KcLQUi4U8KPC1G1xLloARYcURt7P89ThXPKq8FOJsBuE29PtPdIBX3fGTlqzkjCemGbLIfrVdMSul7HX-fiA35EkThNFabmZ0-uZWI9YIORHakw1nID4nTeTfNf36aJ3zJ3vqBgqOEA3-J0TXclCpa2YGQYR3HLBbUgXMHMGfUkNzFe-6jbeHbyPg1zSbVbM0OaH1Tl5gqFvvIXWbzbEP1IXdZeiojzKawGeSnDzqsBxravxWmPnLdSSWTLukxqcS6k9D9NiplFFJs0yybRD0TqB_219rstHsuw