###

POST http://127.0.0.1:3001/channels HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRhMWFmNDJmNWVkYjM2NTQwMjkxNTFjZmUwYmJjZDczOGJkNDI1OWMifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2dnME16TTBOVGs1T0JJR1oybDBhSFZpIiwiYXVkIjoid2VidGVjaC1mcm9udGVuZCIsImV4cCI6MTYwNzg1OTcwOSwiaWF0IjoxNjA3NzczMzA5LCJhdF9oYXNoIjoiVFdyMm14MXJkWVJVdWZ1Um5GQXRMdyIsImVtYWlsIjoibWRlY2FtcG91QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.WG1kT8K2RXeafhGT9fWVbBwl3DCQYo1m69UEEEJWHWlsymhEaj2QFpyOE_UtzRdW_cfBY5jVVqW5rDDwfdMjM04CyNjGfJLs2kY2wjAeGTOIUQnmcEOKuq6O71PIa4pXAzHaAQeU2sqUV85K3kjxsMp5S945d7xuA71To4A6WKX8loc2b1hF1_HldOFMEr0fkLwlhJMzGzHnONCjCiZjep9yWTZGzS3Dd5V5oH6rCkUCrJ1Nr_EDhOMeq1WQnEAshdK6vJm68srUkwoITZj5enMEik87GkdjMALEwRBrwi0jmTe82-rjXyoJZfTs50XAPxW6_FmYM1oYOGk1N4NAyw

{
  "name": "Hey",
  "members": ["Matheiu","Oui"]
}